package org.modbus.client;

import java.net.InetAddress;

import org.modbus.annotation.Quantity;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.node.ObjectNode;

/**
 * Database Table Remarks:
 * 机器设备的基本信息
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table robot
 */
public class KwRobot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.id
     *
     * @mbg.generated
     */
    @Quantity(5)
    @JsonProperty("bookName")
    public Integer id;

    /**
     * Database Column Remarks:
     * 机器名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.name
     *
     * @mbg.generated
     */
    public String name;

    /**
     * Database Column Remarks:
     * 扩展字段
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.expand
     *
     * @mbg.generated
     */
    public ObjectNode expand;

    /**
     * Database Column Remarks:
     * 设备IP地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.ip
     *
     * @mbg.generated
     */
    public InetAddress ip;
}